server:
  port: 10010
spring:
  application:
    name:
      gateway

eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
zuul:
  routes:
    product-service: /product-producer/**
#      path: /product-producer/** # 这里是映射路径
#      url:http http://127.0.0.1:10086 :服务提供者的真是地址
#      ↓@EnableDiscoveryClient 可以从注册中心通过serviceId获得提供者列表，负载均衡
#      serviceId: product-producer # 映射路径对应的实际url地址